lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .github
  - .vscode
  - _site
  - .jekyll-cache
  - .jekyll-metadata
plugins:
  - jekyll-feed
  - jekyll-sitemap
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
