lsi: false
safe: true
source: .
destination: ./docs # Carpeta donde se generará el sitio compilado
incremental: false
highlighter: rouge
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - docs # Evitar bucle infinito de generación
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
